name: CI - Lint & Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust Node version as needed

      - name: Install dependencies and run tests
        run: |
          cd backend
          npm install
          npm test
